version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    image: auth-service
    container_name: auth-service
    restart: always
    hostname: "auth-server"
    depends_on:
      - auth-db
    environment:
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_DB_URI=mongodb://root:pass@auth-db:27017
    networks:
      - network

  auth-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    # Docker healtcheck - checks if database is "alive"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - auth-db_store:/data/db
    networks:
      - network

  # NoSQL: MognoExpress
  auth-db-mongo-express:
    image: mongo-express
    restart: always
    environment:
      # hostname of mongo databse
      - ME_CONFIG_MONGODB_SERVER=auth-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - auth-db
    ports:
      - "8081:8081"
    volumes:
      - auth-db-mongo-express:/data/db

  api-gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    hostname: api-gateway
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - auth-service
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  auth-db-mongo-express:
  auth-db_store:
